### ISSUE TITLE
Is the link still valid?

### ISSUE THREAD

**Issue by yogesh-desai** [digitalcraftsman/sudoku#1]
Hello,

I think the link provided in the description (Readme.md),  is not valid anymore. Could you please check and update the correct link?

Thank you.

**Comment by digitalcraftsman** [comment]
Hello @yogesh-desai,

the organizers of this challenge stopped the challenges after the number of participants was decreasing. In consequence they took down the website that is linked in the README. Hence the link can't be updated. Should the link be removed instead?

**Comment by yogesh-desai** [comment]
Hello @digitalcraftsman,

I have removed the broken link and created a pull request. Please accept it. #2

**Comment by yogesh-desai** [comment]
The issue has been resolved, so closing it.
